dist: trusty
sudo: false

language: c

compiler:
    - clang
    - gcc

addons:
    apt:
        packages:
            - libsdl2-dev
            - libsdl2-mixer-dev

git:
    depth: 1

script:
    - bin/a2x_new test
    - make A2X_PATH=../../.. --directory=test/build/make --jobs
