dist: trusty
sudo: false

language: c

compiler:
    - clang
    - gcc

addons:
    apt:
        packages:
            - libsdl2-dev
            - libsdl2-mixer-dev

script:
    - make --directory=make/a2x --jobs
