language: c

dist: trusty
sudo: required

before_install:
    - sudo apt update -qq
    - sudo apt --assume-yes --install-suggests -qq install python3 libpng12-dev libsdl2-dev libsdl2-mixer-dev

compiler:
    - clang
    - gcc

script:
    - ./bin/a2x_install
